# Generated by Django 4.1.1 on 2022-10-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
